### ISSUE TITLE
State of shs_classes

### ISSUE THREAD

**Issue by RYNO8** [hellodavie/shs_classes#8]
Alex would like to say he that he is very annoyed, because the timetable is not centered

:(

**Comment by RYNO8** [comment]
Henry would like to add that when you hover over the sidebar elements, it does not appear responsive.

**Comment by delilahw** [comment]
David would like you guys to fork the repo and make changes as you see fit. Deploy it yourselves, or make a PR if you feel like it ✨

Going along the same lines as the post from the IT dept. on the student portal, none of us (the old boys) have the time to make patches. This app passed through other alumni before it landed in my hands, and I think it's about time someone from the school took on the responsibility to improve upon the two current apps, or come up with a completely new design.
